### ISSUE TITLE
WoT11

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-wot#1]
Requirement WoT11 "Each thing is described by a WoT Thing Description"

@fserena Can a thing be described by more than one Thing Description? For example, it could be described by Thing Descriptions hosted in two different servers that aggregate TDs.

**Comment by fserena** [comment]
Yes, it may well be. Not only because TDs may be hosted in different servers, but also due to the same thing could be seen and interacted in different ways.

**Comment by rgcmme** [comment]
Even if we don't represent this using axioms, maybe it is useful to include in the documentation of the class/property that fact?

**Comment by mariapoveda** [comment]
+1
