### ISSUE TITLE
WoT15

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-wot#2]
WoT15 "What is a property?"

@fserena could you provide a definition o list of properties/attributes for properties in the Web Thing context?

**Comment by fserena** [comment]
@mariapoveda the definition provided in http://w3c.github.io/wot/current-practices/wot-practices.html#property is good: "_Property provides readable and/or writeable data that can be static (e.g., supported mode, rated output voltage, etc.) or dynamic (e.g., current fill level of water, minimum recorded temperature, etc.)._".

Is that enough? Or are you asking for another kind of definition?

**Comment by rgcmme** [comment]
Right now the definition in the ontology is that a property is "An aspect of an entity that can be observable by a sensor.". Even if I'm not happy with the W3C WoT definition, we need to include the action of actuation apart from sensing in the definition.

**Comment by mariapoveda** [comment]
I was referring to which attributes does a property have but we already got some from the WG documentation.
