### ISSUE TITLE
WoT5 and relation with Thing

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-wot#5]
@fserena What is the relation between a WoT interface and a Thing(Entity)?

**Comment by fserena** [comment]
A WoT interface _provides Web resources that implement the interaction patterns of Properties, Actions, and Events_. Each web resource acts as a mediator/proxy (web interface) between the Thing and their clients.

**Comment by rgcmme** [comment]
Isn't this issue already solved with the Endpoint class?

**Comment by mariapoveda** [comment]
Yes, for now the interface itself is not represented as a concept, we have Endpoint and Interaction Patterns.
